// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "ToolSet/DataTypes/HandyManDataTypes.h"
#include "ToolSet/HandyManBaseClasses/HandyManSingleClickTool.h"
#include "IvyCreator_PCG.generated.h"

/**
 * 
 */
UCLASS()
class HANDYMAN_API UIvyCreator_PCG : public UHandyManSingleClickTool
{
	GENERATED_BODY()
public:
	UIvyCreator_PCG();

	virtual void Setup() override;

	// Click
	//virtual FInputRayHit TestIfHitByClick_Implementation(FInputDeviceRay ClickPos, const FScriptableToolModifierStates& Modifiers) override;
	virtual void OnHitByClick_Implementation(FInputDeviceRay ClickPos, const FScriptableToolModifierStates& Modifiers) override;

	// Hover API
	virtual void OnHoverBegin_Implementation(FInputDeviceRay HoverPos, const FScriptableToolModifierStates& Modifiers) override;
	virtual FInputRayHit OnHoverHitTest_Implementation(FInputDeviceRay HoverPos, const FScriptableToolModifierStates& Modifiers) override;
	virtual bool OnHoverUpdate_Implementation(FInputDeviceRay HoverPos, const FScriptableToolModifierStates& Modifiers) override;
	virtual void OnHoverEnd_Implementation(const FScriptableToolModifierStates& Modifiers) override;
	virtual void OnTick(float DeltaTime) override;
	virtual void Shutdown(EToolShutdownType ShutdownType) override;

	virtual void UpdateAcceptWarnings(EAcceptWarning Warning) override;
	virtual bool CanAccept() const override;
	virtual bool HasCancel() const override;

	void HandleAccept();
	void HandleCancel();

private:
	
	UPROPERTY()
	class UIvyCreator_PCG_PropertySet* PropertySet;

	UPROPERTY()
	TMap<AActor*, FObjectSelection> SelectedActors;

	void HighlightActors(FInputDeviceRay ClickPos, const FScriptableToolModifierStates& Modifiers, bool bShouldEditSelection = false);
	void HighlightSelectedActor(const FScriptableToolModifierStates& Modifiers, bool bShouldEditSelection, const FHitResult& HitResult);

	

};

USTRUCT()
struct FIvyCreatorData
{
	GENERATED_BODY()

	
	
};

UCLASS()
class HANDYMAN_API UIvyCreator_PCG_PropertySet : public UScriptableInteractiveToolPropertySet
{
	GENERATED_BODY()

public:
	UIvyCreator_PCG_PropertySet();
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "Change the global seed of the entire PCG Graph instance for each tool in the level."))
	int32 RandomSeed = 1499;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "The maximum amount of splines that will be generated by the system."))
	int32 SplineCount = 5;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn.", ClampMin = "0.1", ClampMax = "1.0"))
	float StartingPointsHeightRatio = 0.8f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far down the meshes the vertical axis will the ending points spawn.", ClampMin = "0.1", ClampMax = "1.0"))
	float EndingPointsHeightRatio = 0.8f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "Change the global seed of the entire PCG Graph instance for each tool in the level.", ClampMin = "5", ClampMax = "100"))
	int32 PathComplexity = 25;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn.", UIMin = "0.1", UIMax = "3.0"))
	float VineThickness = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	float MeshOffsetDistance = 10.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	float LeafDensity = 10.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	FVector2D LeafScaleRange = FVector2D(1.0f, 1.0f);

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	bool bUseRandomLeafRotation = false;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (EditCondition = "bUseRandomLeafRotation", Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	FRotator MinRandomRotation = FRotator();

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (EditCondition = "bUseRandomLeafRotation", Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	FRotator MaxRandomRotation = FRotator();

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	bool bUseRandomLeafOffset = false;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (EditCondition = "bUseRandomLeafOffset", Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	FVector MinRandomOffset = FVector();

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Settings", meta = (EditCondition = "bUseRandomLeafOffset", Tooltip = "This will determine how far up the meshes the vertical axis will the starting points spawn."))
	FVector MaxRandomOffset = FVector();

	

	
};
